name: "vprofile IAC"
on: 
  push:
    branches:
      - main
      - stage
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths: 
      - terraform/** 

env:
  # Credentials for AWS
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
  AWS_REGION: us-east-2
  EKS_CLUSTER: vprofile-eks


jobs:
  terraform:
    name: "apply terraform code changes"
    #elrunner 3ashan github actions feh containers (runners) keter
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    #efta7 GitHub market place 3shan feh el pre-built runner steps ele momkn te5tsr el dnia msh lazm apt install
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: setup terraform with specified version on the runner (elcontainer bel ubuntu img)
        uses: hashicorp/setup-terraform@v2

      - name: Terraform initialization
        id: init 
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      
      #- name: Terraform Format
       # id: fmt
       # run: terraform fmt -check
        # if the format of this code is not correct the workflow will fail

      - name: terraform validation
        id: validate
        run: terraform validate

      - name: terraform planning
        id: plan
        # no color 3shan el gpu, no input hytlobo, we hystore el output fe file esmo planfile, da 3shan kan feh bug fa to avoid parallel exec on TF
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: terraform plan status
        if: steps.plan.outcome == 'failure'
        # law 7asal failure fel plan hn KILL el container
        run: exit 1  